/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BaseComponent: typeof import('./src/components/BaseComponent.vue')['default']
    ChartJs: typeof import('./src/components/Home/ChartJs.vue')['default']
    CsieNtust: typeof import('./src/components/Home/CsieNtust.vue')['default']
    CsimNtust: typeof import('./src/components/Home/CsimNtust.vue')['default']
    Docker: typeof import('./src/components/Home/Docker.vue')['default']
    FoonYew: typeof import('./src/components/Home/FoonYew.vue')['default']
    Git: typeof import('./src/components/Home/Git.vue')['default']
    Jquery: typeof import('./src/components/Home/Jquery.vue')['default']
    Laravel: typeof import('./src/components/Home/Laravel.vue')['default']
    Linux: typeof import('./src/components/Home/Linux.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Nginx: typeof import('./src/components/Home/Nginx.vue')['default']
    PHP: typeof import('./src/components/Home/PHP.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopButton: typeof import('./src/components/TopButton.vue')['default']
    Vue: typeof import('./src/components/Home/Vue.vue')['default']
    Vuetify: typeof import('./src/components/Home/Vuetify.vue')['default']
  }
}
